from thecodingmachine/php:8.0-v4-apache-node14

RUN wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb
RUN sudo dpkg -i packages-microsoft-prod.deb
RUN sudo apt-get update
RUN sudo apt-get install powershell  -y
RUN sudo apt-get install curl -y
RUN sudo apt-get install unzip  -y
RUN sudo apt-get install xvfb  -y
RUN sudo apt-get install libxi6  -y
RUN sudo apt-get install libgconf-2-4 -y
RUN sudo apt-get install default-jdk  -y
RUN sudo apt-get install firefox-geckodriver -y
RUN sudo apt-get install screen -y

